export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL';

export const BOOKING_LIST_MY_REQUEST = 'BOOKING_LIST_MY_REQUEST';
export const BOOKING_LIST_MY_SUCCESS = 'BOOKING_LIST_MY_SUCCESS';
export const BOOKING_LIST_MY_FAIL = 'BOOKING_LIST_MY_FAIL';